id: 'tv_on_sonos_off'
initial_state: 'on'
alias: 'TV on Sonos off'
trigger:
  - platform: state
    entity_id: media_player.lounge_tcl_roku_tv
    to: 'on'
condition:
  - condition: state
    entity_id: media_player.living_room
    state: 'playing'
action:
  - service: media_player.media_stop
    entity_id: media_player.living_room
