image_analyzer:
  name: Image Analyzer
  description: Analyze an image with AI
  fields:
    provider:
      name: Provider
      description: 'Configuration to use'
      required: true
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      required: false
      description: 'Model to use. Uncheck for default.'
      example: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Model prompt'
      example: "Describe the image"
      selector:
        text:
          multiline: true
    remember:
      name: Remember
      required: false
      description: 'Store this event in the timeline'
      example: true
      default: false
      selector:
        boolean:
    use_memory:
      name: Use Memory
      required: false
      description: 'Use information stored in memory to provide additional context. Memory must be set up.'
      example: true
      default: false
      selector:
        boolean:
    image_file:
      name: Image File
      required: false
      description: 'Local path to image'
      example: "/config/www/tmp/front_door.jpg"
      selector:
        text:
          multiline: true
    image_entity:
      name: Image Entity
      required: false
      description: 'Image or camera entity to analyze'
      example: 'image.front_door_person'
      selector:
        entity:
          domain: ["image", "camera"]
          multiple: true
    include_filename:
      name: Include Filename
      required: true
      description: 'Include filename in the request'
      example: false
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: false
      example: 3000
      default: 3000
      selector:
        number:
    generate_title:
      name: Generate Title
      required: false
      description: Generate a title. (Used for notifications and remembered events)
      default: false
      selector:
        boolean:
    expose_images:
      name: Expose Images
      description: Save the key frame. This will save analyzed frames in /media/llmvision/snapshots so they can be used for notifications. The file path will be included in the response.
      required: false
      example: false
      default: false
      selector:
        boolean:

video_analyzer:
  name: Video Analyzer
  description: Analyze video with AI
  fields:
    provider:
      name: Provider
      description: 'Configuration to use'
      required: true
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      required: false
      description: 'Model to use. Uncheck for default.'
      example: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Model prompt'
      example: "Describe what happens in the video"
      selector:
        text:
          multiline: true
    remember:
      name: Remember
      required: false
      description: 'Store this event in the timeline'
      example: true
      default: false
      selector:
        boolean:
    use_memory:
      name: Use Memory
      required: false
      description: 'Use information stored in memory to provide additional context. Memory must be set up.'
      example: true
      default: false
      selector:
        boolean:
    video_file:
      name: Video File
      required: false
      description: 'One or multiple local paths or URLs to video. Use a new line to separate multiple entries.'
      example: "/config/www/recordings/front_door.mp4"
      selector:
        text:
          multiline: true
    event_id:
      name: Frigate Event ID
      required: false
      description: 'Frigate Event ID'
      example: 1712108310.968815-r28cdt
      selector:
        text:
          multiline: true
    max_frames:
      name: Max Frames
      description: How many frames to analyze. Picks frames with the most movement.
      required: false
      example: 3
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
    include_filename:
      name: Include Filename
      required: true
      description: 'Include filename in the request'
      example: false
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: false
      example: 3000
      default: 3000
      selector:
        number:
    generate_title:
      name: Generate Title
      required: false
      description: Generate a title. (Used for notifications and remembered events)
      default: false
      selector:
        boolean:
    expose_images:
      name: Expose Images
      description: Save the key frame. This will save analyzed frames in /media/llmvision/snapshots so they can be used for notifications. The file path will be included in the response.
      required: false
      example: false
      default: false
      selector:
        boolean:

stream_analyzer:
  name: Stream Analyzer
  description: Analyze a live camera stream with AI
  fields:
    provider:
      name: Provider
      description: 'Configuration to use'
      required: true
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      required: false
      description: 'Model to use. Uncheck for default.'
      example: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Model prompt'
      example: "Describe what happens in the camera feed"
      selector:
        text:
          multiline: true
    remember:
      name: Remember
      required: false
      description: 'Store this event in the timeline'
      example: true
      default: false
      selector:
        boolean:
    use_memory:
      name: Use Memory
      required: false
      description: 'Use information stored in memory to provide additional context. Memory must be set up.'
      example: true
      default: false
      selector:
        boolean:
    image_entity:
      name: Camera Entity
      required: true
      description: 'Camera entity to stream'
      example: 'camera.front_door'
      selector:
        entity:
          domain: ["camera"]
          multiple: true
    duration:
      name: Recording Duration
      required: true
      description: 'How long to record in seconds'
      example: 5
      default: 5
      selector:
        number:
          min: 1
          max: 60
    max_frames:
      name: Max Frames
      description: How many frames to analyze. Picks frames with the most movement.
      required: false
      example: 3
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
    include_filename:
      name: Include camera name
      required: true
      description: 'Include camera name in request'
      example: false
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: false
      example: 3000
      default: 3000
      selector:
        number:
    generate_title:
      name: Generate Title
      required: false
      description: Generate a title. (Used for notifications and remembered events)
      default: false
      selector:
        boolean:
    expose_images:
      name: Expose Images
      description: Save the key frame. This will save analyzed frames in /media/llmvision/snapshots so they can be used for notifications. The file path will be included in the response.
      required: false
      example: false
      default: false
      selector:
        boolean:

data_analyzer:
  name: Data Analyzer
  description: Update sensors with data extracted from images (Beta)
  fields:
    provider:
      name: Provider
      description: 'Configuration to use'
      required: true
      selector:
        config_entry:
          integration: llmvision
    model:
      name: Model
      required: false
      description: 'Model to use. Uncheck for default.'
      example: "gpt-4o-mini"
      selector:
        text:
          multiline: false
    message:
      name: Prompt
      required: true
      description: 'Describe what should be extracted from the image. Data types and available options will be recognized automatically based the provided sensor.'
      example: "How many cars are parked?"
      default: "How many cars are parked?"
      selector:
        text:
          multiline: true
    remember:
      name: Remember
      required: false
      description: 'Store this event in the timeline'
      example: true
      default: false
      selector:
        boolean:
    use_memory:
      name: Use Memory
      required: false
      description: 'Use information stored in memory to provide additional context. Memory must be set up.'
      example: true
      default: false
      selector:
        boolean:
    sensor_entity:
      name: Sensor Entity
      description: The sensor to update
      required: true
      selector:
        entity:
          multiple: false
          filter:
            domain: ["number", "input_number", "text", "input_text", "input_boolean", "select", "input_select"]
    image_file:
      name: Image File
      required: false
      description: 'Local path to image'
      example: "/config/www/tmp/front_door.jpg"
      selector:
        text:
          multiline: true
    image_entity:
      name: Image Entity
      required: false
      description: 'Image or camera entity to analyze'
      example: 'image.front_door_person'
      selector:
        entity:
          domain: ["image", "camera"]
          multiple: true
    include_filename:
      name: Include Filename
      required: true
      description: 'Include filename in the request'
      example: false
      default: false
      selector:
        boolean:
    target_width:
      name: Target Width
      required: false
      description: 'Width in pixels to downscale'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 1920
    max_tokens:
      name: Maximum Tokens
      description: 'Maximum number of tokens to generate'
      required: false
      example: 3000
      default: 3000
      selector:
        number:
    generate_title:
      name: Generate Title
      required: false
      description: Generate a title. (Used for notifications and remembered events)
      default: false
      selector:
        boolean:
    expose_images:
      name: Expose Images
      description: Save the key frame. This will save analyzed frames in /media/llmvision/snapshots so they can be used for notifications. The file path will be included in the response.
      required: false
      example: false
      default: false
      selector:
        boolean:

remember:
  name: Remember
  description: Remember an event in the LLM Vision Timeline
  fields:
    title:
      name: Title
      required: true
      description: 'Event Title'
      example: "Car seen"
      selector:
        text:
          multiline: false
    summary:
      name: Summary
      required: true
      description: 'Event Description'
      example: "A car was seen pulling into a driveway"
      selector:
        text:
          multiline: true
    image_path:
      name: Image Path
      required: false
      description: Image of the event. Must be stored in "/media/llmvision/snapshots/"
      example: '/config/media/llmvision/snapshots/example.jpg'
      selector:
        text:
          multiline: false
    camera_entity:
      name: Camera Entity
      required: false
      description: Camera that recorded the event.
      example: 'camera.front_door'
      selector:
        entity:
          domain: camera
          multiple: false
    start_time:
      name: Start Time and Date
      required: false
      description: 'Time and date the event started. Set to now if left blank. Format: (YYYY-MM-DD HH:MM:SS)'
      example: '2022-02-22 13:30:00'
      selector:
        datetime:
    end_time:
      name: End Time and Date
      required: false
      description: 'Time and date the event ended. Set to one minute after start if left blank. Format: (YYYY-MM-DD HH:MM:SS)'
      example: '2022-02-22 13:30:00'
      selector:
        datetime:
