id: 'alarm_disarm_in_the_morning'
initial_state: 'on'
alias: 'Alarm disarm in the morning'
triggers:
  - trigger: state
    entity_id: input_boolean.bedtime
    to: 'off'
  - trigger: state
    entity_id: binary_sensor.utility_motion_occupancy
    to: 'on'
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel.master
        state: 'disarmed'
actions:
  - action: alarmo.disarm
    data:
      entity_id: alarm_control_panel.master
