id: 'alarm_arm_away'
initial_state: 'on'
alias: 'Alarm arm away'
triggers:
  - trigger: numeric_state
    entity_id: zone.home
    below: 1
actions:
  - action: alarmo.arm
    data:
      entity_id: alarm_control_panel.master
      mode: away
