id: 'office_unoccupied'
initial_state: 'on'
alias: 'Office unoccupied'
triggers:
  - trigger: state
    entity_id: input_boolean.office_occupied
    to: 'off'
actions:
  - parallel:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.stream_front_camera_motion
      - action: input_boolean.turn_on
        target:
          entity_id: 
            - input_boolean.lighting_living_room
            - input_boolean.lighting_office
