id: 'awtrix_master_bedroom_clock_colour'
alias: 'awtrix master bedroom clock colour'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person2_is_awake
    to: 'on'
    from: 'off'
    id: 'awake'
  - platform: state
    entity_id: input_boolean.person2_is_awake
    to: 'off'
    from: 'on'
    id: 'asleep'
  - platform: state
    entity_id: input_boolean.person2_in_bed
    to: 'on'
    from: 'off'
    id: 'bed'
action:
  - choose:
      - conditions:
          - condition: trigger
            id: 'awake'
        sequence:
          - alias: "White"
            service: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: awtrix_master/settings
              payload: >-
                { "TIME_COL": [255,255,255], "CBCOL": [255, 255, 255] }
      - conditions:
          - condition: trigger
            id: 'bed'
        sequence:
          - alias: "Amber"
            service: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: awtrix_master/settings
              payload: >-
                { "TIME_COL": [255,165,0] }
      - conditions:
          - condition: trigger
            id: 'asleep'
        sequence:
          - alias: "Red"
            service: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: awtrix_master/settings
              payload: >-
                { "TIME_COL": [128,0,0] }
    default:
      - alias: "Default white"
        service: mqtt.publish
        data:
          qos: 0
          retain: false
          topic: awtrix_master/settings
          payload: >-
            { "TIME_COL": [255,255,255], "CBCOL": [255, 255, 255] }
