id: 'office_humidifier_control'
alias: 'Office humidifier control'
initial_state: 'on'
mode: queued
triggers:
  - trigger: state
    entity_id: input_boolean.office_occupied
    to: 'on'
    id: 'occupied'
    for: '00:01:00'
  - trigger: state
    entity_id: input_boolean.office_occupied
    to: 'off'
    for: '00:01:00'
    id: 'unoccupied'
  - trigger: state
    entity_id: group.work_laptop
    to: 'not_home'
    id: 'away'
  - trigger: state
    entity_id: input_boolean.office_paused
    to: 'on'
    id: 'paused'
  - trigger: state
    entity_id: input_boolean.office_paused
    to: 'off'
    id: 'unpaused'
actions:
  - choose:
        # Room occupied, turn it on
      - conditions:
          - condition: trigger
            id: 'occupied'
          - condition: state
            entity_id: humidifier.dual_200s
            state: 'off'
          - condition: state
            entity_id: binary_sensor.dual_200s_low_water
            state: 'off'
          - condition: state
            entity_id: binary_sensor.dual_200s_water_tank_lifted
            state: 'off'
        sequence:
          - action: humidifier.turn_on
            target:
              entity_id: humidifier.dual_200s
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.office_humidifier
        # Room empty, turn it off
      - conditions:
          - condition: state
            entity_id: input_boolean.office_occupied
            state: 'off'
          - condition: state
            entity_id: group.work_laptop
            state: 'not_home'
        sequence:
          - action: humidifier.turn_off
            target:
              entity_id: humidifier.dual_200s
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.office_humidifier
        # Set it to low
      - conditions:
          - condition: trigger
            id: 'paused'
          - condition: state
            entity_id: humidifier.dual_200s
            state: 'on'
        sequence:
          - action: number.set_value
            target:
              entity_id: number.dual_200s_mist_level
            data:
              value: 1
        # Set it back to auto
      - conditions:
          - condition: trigger
            id: 'unpaused'
          - condition: state
            entity_id: humidifier.dual_200s
            state: 'on'
        sequence:
          - action: humidifier.set_mode
            data:
              mode: auto
            target:
              entity_id: humidifier.dual_200s
