id: 'office_meeting_started'
initial_state: 'on'
alias: 'Office meeting started'
triggers:
  - trigger: state
    entity_id: calendar.person2_work
    to: 'on'
    id: calendar
  - trigger: calendar
    entity_id: calendar.person2_work
    event: start
    id: calendar
  - trigger: state
    entity_id: binary_sensor.kelsie_webcamactive
    to: 'on'
    id: webcam
  - trigger: state
    entity_id: input_boolean.office_occupied
    to: 'off'
    id: unoccupied
  - trigger: state
    entity_id: input_boolean.office_paused
    to: 'on'
    id: paused
conditions:
  - condition: state
    entity_id: switch.home_assistant_voice_0907a0_mute
    state: 'off'
actions:
  - parallel:
      - service: switch.turn_on
        data:
          entity_id: switch.home_assistant_voice_0907a0_mute
      - action: number.set_value
        target:
          entity_id: number.dual_200s_mist_level
        data:
          value: 1
