id: 'office_calendar_reminder'
alias: 'Office calendar reminder'
initial_state: 'on'
triggers:
  - trigger: calendar
    entity_id: calendar.reminders
    event: start
conditions:
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'on'
actions:
  - action: media_player.play_media
    data:
      media_content_id: >-
        media-source://tts/tts.piper?message={{ trigger.calendar_event.summary|replace("Reminder: ","") }}
      media_content_type: music
      announce: true
      extra:
        volume: 20
    target:
      entity_id: media_player.office_sonos_cloud
