id: 'office_meeting_ended'
initial_state: 'on'
alias: 'Office meeting ended'
triggers:
  - trigger: state
    entity_id: calendar.person2_work
    to: 'off'
    id: calendar
  - trigger: calendar
    entity_id: calendar.person2_work
    event: end
    id: calendar
  - trigger: state
    entity_id: binary_sensor.kelsie_webcamactive
    to: 'off'
    id: webcam
  - trigger: state
    entity_id: input_boolean.office_occupied
    to: 'on'
    id: occupied
  - trigger: state
    entity_id: binary_sensor.office_mmwave_region_1
    to: 'on'
    id: presence
  - trigger: state
    entity_id: input_boolean.office_paused
    to: 'off'
    id: paused
  - trigger: state
    entity_id: input_select.office
    to: 'Motion'
    id: select
  - trigger: state
    entity_id: media_player.office
    to: 'playing'
conditions:
  - condition: state
    entity_id: switch.home_assistant_voice_0907a0_mute
    state: 'on'
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.office_occupied
        state: 'on'
      - condition: state
        entity_id: input_select.office
        state: 'Motion'
      - condition: trigger
        id: presence
actions:
  - parallel:
      - action: switch.turn_off
        data:
          entity_id: switch.home_assistant_voice_0907a0_mute
      - action: humidifier.set_mode
        data:
          mode: auto
        target:
          entity_id: humidifier.dual_200s
