id: 'office_unoccupied_window_open'
alias: 'Office unoccupied window open'
trigger:
  - platform: state
    entity_id: input_boolean.office_occupied
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'off'
  - condition: state
    entity_id: binary_sensor.office_window_contact
    state: 'on'
  - condition: state
    entity_id: group.work_laptop
    state: 'not_home'
action:
  - service: notify.person2
    data:
      message: "You left the office window open"
