id: 'person2_awake'
alias: 'person2 awake'
initial_state: 'on'
trigger:
  # Phone or tablet is unplugged
  - platform: state
    entity_id: 
      - input_boolean.person2_phone_charging
      - input_boolean.person2_tablet_charging
    to: 'off'
    id: 'unplugged'
  # Fully awake
  - platform: state
    entity_id: event.sleep_as_android_sleep_phase
    to: 'awake'
    id: 'stopped'
  # Alarm dismissed
  - platform: state
    entity_id: event.sleep_as_android_alarm_clock
    to: 'alert_dismiss'
    id: 'alarm'
condition:
  - condition: state
    entity_id: input_boolean.person2_is_awake
    state: 'off'
  - condition: or
    conditions:
      # Either the alarm is playing or I unplugged the phone/tablet
      - condition: trigger
        id: 'alarm'
      - condition: trigger
        id: 'unplugged'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_is_awake
  - service: input_boolean.turn_off
    entity_id: 
      - input_boolean.person2_in_bed
      - input_boolean.person2_pre_alarm
  - service: script.turn_on
    entity_id: script.person2_travel_sensor
